---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwibot
  namespace: kiwi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwibot
  template:
    metadata:
      namespace: kiwi
      labels:
        app: kiwibot
    spec:
      containers:
      - name: kiwibot
        image: fogapod/kiwibot
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              # for ping command
              - NET_RAW
        volumeMounts:
          - name: config
            mountPath: /code/config.json
            subPath: config.json
            readOnly: true
          - name: ssh-key
            mountPath: /home/kiwi/.ssh/id_ed25519
            subPath: id_ed25519
            readOnly: true
          # see below
          - name: testing-modules
            mountPath: /code/modules/testing
      volumes:
        - name: config
          secret:
            secretName: kiwibot-config
        - name: ssh-key
          secret:
            secretName: kiwibot-repo-key
        # can be safely removed
        - name: testing-modules
          persistentVolumeClaim:
            claimName: kiwibot-testing-modules
      # This is required because I hardcoded redis host to localhost
      hostNetwork: true
      nodeSelector:
        type: kiwi

# I only use these because I had old directory with modules.
# Volume and Claim can be safely removed.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwibot-testing-modules
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kiwibot-testing-modules
  local:
    path: /home/kiwi/OldKiwiBot/modules/testing
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
            - kiwi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwibot-testing-modules
  namespace: kiwi
spec:
  storageClassName: kiwibot-testing-modules
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
